// Machine-generated file.
// See http://winterdrache.de/bindings for details.

package sdl

// #cgo linux freebsd darwin pkg-config: sdl2
// #include <SDL.h>
import "C"

 // Defines constants which identify keyboard keys and modifiers.

const (
    SDLK_SCANCODE_MASK = C.SDLK_SCANCODE_MASK

    KMOD_CTRL = C.KMOD_CTRL

    KMOD_SHIFT = C.KMOD_SHIFT

    KMOD_ALT = C.KMOD_ALT

    KMOD_GUI = C.KMOD_GUI
)

const (
    SDLK_UNKNOWN  = C.SDLK_UNKNOWN

    SDLK_RETURN  = C.SDLK_RETURN

    SDLK_ESCAPE  = C.SDLK_ESCAPE

    SDLK_BACKSPACE  = C.SDLK_BACKSPACE

    SDLK_TAB  = C.SDLK_TAB

    SDLK_SPACE  = C.SDLK_SPACE

    SDLK_EXCLAIM  = C.SDLK_EXCLAIM

    SDLK_QUOTEDBL  = C.SDLK_QUOTEDBL

    SDLK_HASH  = C.SDLK_HASH

    SDLK_PERCENT  = C.SDLK_PERCENT

    SDLK_DOLLAR  = C.SDLK_DOLLAR

    SDLK_AMPERSAND  = C.SDLK_AMPERSAND

    SDLK_QUOTE  = C.SDLK_QUOTE

    SDLK_LEFTPAREN  = C.SDLK_LEFTPAREN

    SDLK_RIGHTPAREN  = C.SDLK_RIGHTPAREN

    SDLK_ASTERISK  = C.SDLK_ASTERISK

    SDLK_PLUS  = C.SDLK_PLUS

    SDLK_COMMA  = C.SDLK_COMMA

    SDLK_MINUS  = C.SDLK_MINUS

    SDLK_PERIOD  = C.SDLK_PERIOD

    SDLK_SLASH  = C.SDLK_SLASH

    SDLK_0  = C.SDLK_0

    SDLK_1  = C.SDLK_1

    SDLK_2  = C.SDLK_2

    SDLK_3  = C.SDLK_3

    SDLK_4  = C.SDLK_4

    SDLK_5  = C.SDLK_5

    SDLK_6  = C.SDLK_6

    SDLK_7  = C.SDLK_7

    SDLK_8  = C.SDLK_8

    SDLK_9  = C.SDLK_9

    SDLK_COLON  = C.SDLK_COLON

    SDLK_SEMICOLON  = C.SDLK_SEMICOLON

    SDLK_LESS  = C.SDLK_LESS

    SDLK_EQUALS  = C.SDLK_EQUALS

    SDLK_GREATER  = C.SDLK_GREATER

    SDLK_QUESTION  = C.SDLK_QUESTION

    SDLK_AT  = C.SDLK_AT

    SDLK_LEFTBRACKET  = C.SDLK_LEFTBRACKET

    SDLK_BACKSLASH  = C.SDLK_BACKSLASH

    SDLK_RIGHTBRACKET  = C.SDLK_RIGHTBRACKET

    SDLK_CARET  = C.SDLK_CARET

    SDLK_UNDERSCORE  = C.SDLK_UNDERSCORE

    SDLK_BACKQUOTE  = C.SDLK_BACKQUOTE

    SDLK_a  = C.SDLK_a

    SDLK_b  = C.SDLK_b

    SDLK_c  = C.SDLK_c

    SDLK_d  = C.SDLK_d

    SDLK_e  = C.SDLK_e

    SDLK_f  = C.SDLK_f

    SDLK_g  = C.SDLK_g

    SDLK_h  = C.SDLK_h

    SDLK_i  = C.SDLK_i

    SDLK_j  = C.SDLK_j

    SDLK_k  = C.SDLK_k

    SDLK_l  = C.SDLK_l

    SDLK_m  = C.SDLK_m

    SDLK_n  = C.SDLK_n

    SDLK_o  = C.SDLK_o

    SDLK_p  = C.SDLK_p

    SDLK_q  = C.SDLK_q

    SDLK_r  = C.SDLK_r

    SDLK_s  = C.SDLK_s

    SDLK_t  = C.SDLK_t

    SDLK_u  = C.SDLK_u

    SDLK_v  = C.SDLK_v

    SDLK_w  = C.SDLK_w

    SDLK_x  = C.SDLK_x

    SDLK_y  = C.SDLK_y

    SDLK_z  = C.SDLK_z

    SDLK_CAPSLOCK  = C.SDLK_CAPSLOCK

    SDLK_F1  = C.SDLK_F1

    SDLK_F2  = C.SDLK_F2

    SDLK_F3  = C.SDLK_F3

    SDLK_F4  = C.SDLK_F4

    SDLK_F5  = C.SDLK_F5

    SDLK_F6  = C.SDLK_F6

    SDLK_F7  = C.SDLK_F7

    SDLK_F8  = C.SDLK_F8

    SDLK_F9  = C.SDLK_F9

    SDLK_F10  = C.SDLK_F10

    SDLK_F11  = C.SDLK_F11

    SDLK_F12  = C.SDLK_F12

    SDLK_PRINTSCREEN  = C.SDLK_PRINTSCREEN

    SDLK_SCROLLLOCK  = C.SDLK_SCROLLLOCK

    SDLK_PAUSE  = C.SDLK_PAUSE

    SDLK_INSERT  = C.SDLK_INSERT

    SDLK_HOME  = C.SDLK_HOME

    SDLK_PAGEUP  = C.SDLK_PAGEUP

    SDLK_DELETE  = C.SDLK_DELETE

    SDLK_END  = C.SDLK_END

    SDLK_PAGEDOWN  = C.SDLK_PAGEDOWN

    SDLK_RIGHT  = C.SDLK_RIGHT

    SDLK_LEFT  = C.SDLK_LEFT

    SDLK_DOWN  = C.SDLK_DOWN

    SDLK_UP  = C.SDLK_UP

    SDLK_NUMLOCKCLEAR  = C.SDLK_NUMLOCKCLEAR

    SDLK_KP_DIVIDE  = C.SDLK_KP_DIVIDE

    SDLK_KP_MULTIPLY  = C.SDLK_KP_MULTIPLY

    SDLK_KP_MINUS  = C.SDLK_KP_MINUS

    SDLK_KP_PLUS  = C.SDLK_KP_PLUS

    SDLK_KP_ENTER  = C.SDLK_KP_ENTER

    SDLK_KP_1  = C.SDLK_KP_1

    SDLK_KP_2  = C.SDLK_KP_2

    SDLK_KP_3  = C.SDLK_KP_3

    SDLK_KP_4  = C.SDLK_KP_4

    SDLK_KP_5  = C.SDLK_KP_5

    SDLK_KP_6  = C.SDLK_KP_6

    SDLK_KP_7  = C.SDLK_KP_7

    SDLK_KP_8  = C.SDLK_KP_8

    SDLK_KP_9  = C.SDLK_KP_9

    SDLK_KP_0  = C.SDLK_KP_0

    SDLK_KP_PERIOD  = C.SDLK_KP_PERIOD

    SDLK_APPLICATION  = C.SDLK_APPLICATION

    SDLK_POWER  = C.SDLK_POWER

    SDLK_KP_EQUALS  = C.SDLK_KP_EQUALS

    SDLK_F13  = C.SDLK_F13

    SDLK_F14  = C.SDLK_F14

    SDLK_F15  = C.SDLK_F15

    SDLK_F16  = C.SDLK_F16

    SDLK_F17  = C.SDLK_F17

    SDLK_F18  = C.SDLK_F18

    SDLK_F19  = C.SDLK_F19

    SDLK_F20  = C.SDLK_F20

    SDLK_F21  = C.SDLK_F21

    SDLK_F22  = C.SDLK_F22

    SDLK_F23  = C.SDLK_F23

    SDLK_F24  = C.SDLK_F24

    SDLK_EXECUTE  = C.SDLK_EXECUTE

    SDLK_HELP  = C.SDLK_HELP

    SDLK_MENU  = C.SDLK_MENU

    SDLK_SELECT  = C.SDLK_SELECT

    SDLK_STOP  = C.SDLK_STOP

    SDLK_AGAIN  = C.SDLK_AGAIN

    SDLK_UNDO  = C.SDLK_UNDO

    SDLK_CUT  = C.SDLK_CUT

    SDLK_COPY  = C.SDLK_COPY

    SDLK_PASTE  = C.SDLK_PASTE

    SDLK_FIND  = C.SDLK_FIND

    SDLK_MUTE  = C.SDLK_MUTE

    SDLK_VOLUMEUP  = C.SDLK_VOLUMEUP

    SDLK_VOLUMEDOWN  = C.SDLK_VOLUMEDOWN

    SDLK_KP_COMMA  = C.SDLK_KP_COMMA

    SDLK_KP_EQUALSAS400  = C.SDLK_KP_EQUALSAS400

    SDLK_ALTERASE  = C.SDLK_ALTERASE

    SDLK_SYSREQ  = C.SDLK_SYSREQ

    SDLK_CANCEL  = C.SDLK_CANCEL

    SDLK_CLEAR  = C.SDLK_CLEAR

    SDLK_PRIOR  = C.SDLK_PRIOR

    SDLK_RETURN2  = C.SDLK_RETURN2

    SDLK_SEPARATOR  = C.SDLK_SEPARATOR

    SDLK_OUT  = C.SDLK_OUT

    SDLK_OPER  = C.SDLK_OPER

    SDLK_CLEARAGAIN  = C.SDLK_CLEARAGAIN

    SDLK_CRSEL  = C.SDLK_CRSEL

    SDLK_EXSEL  = C.SDLK_EXSEL

    SDLK_KP_00  = C.SDLK_KP_00

    SDLK_KP_000  = C.SDLK_KP_000

    SDLK_THOUSANDSSEPARATOR  = C.SDLK_THOUSANDSSEPARATOR

    SDLK_DECIMALSEPARATOR  = C.SDLK_DECIMALSEPARATOR

    SDLK_CURRENCYUNIT  = C.SDLK_CURRENCYUNIT

    SDLK_CURRENCYSUBUNIT  = C.SDLK_CURRENCYSUBUNIT

    SDLK_KP_LEFTPAREN  = C.SDLK_KP_LEFTPAREN

    SDLK_KP_RIGHTPAREN  = C.SDLK_KP_RIGHTPAREN

    SDLK_KP_LEFTBRACE  = C.SDLK_KP_LEFTBRACE

    SDLK_KP_RIGHTBRACE  = C.SDLK_KP_RIGHTBRACE

    SDLK_KP_TAB  = C.SDLK_KP_TAB

    SDLK_KP_BACKSPACE  = C.SDLK_KP_BACKSPACE

    SDLK_KP_A  = C.SDLK_KP_A

    SDLK_KP_B  = C.SDLK_KP_B

    SDLK_KP_C  = C.SDLK_KP_C

    SDLK_KP_D  = C.SDLK_KP_D

    SDLK_KP_E  = C.SDLK_KP_E

    SDLK_KP_F  = C.SDLK_KP_F

    SDLK_KP_XOR  = C.SDLK_KP_XOR

    SDLK_KP_POWER  = C.SDLK_KP_POWER

    SDLK_KP_PERCENT  = C.SDLK_KP_PERCENT

    SDLK_KP_LESS  = C.SDLK_KP_LESS

    SDLK_KP_GREATER  = C.SDLK_KP_GREATER

    SDLK_KP_AMPERSAND  = C.SDLK_KP_AMPERSAND

    SDLK_KP_DBLAMPERSAND  = C.SDLK_KP_DBLAMPERSAND

    SDLK_KP_VERTICALBAR  = C.SDLK_KP_VERTICALBAR

    SDLK_KP_DBLVERTICALBAR  = C.SDLK_KP_DBLVERTICALBAR

    SDLK_KP_COLON  = C.SDLK_KP_COLON

    SDLK_KP_HASH  = C.SDLK_KP_HASH

    SDLK_KP_SPACE  = C.SDLK_KP_SPACE

    SDLK_KP_AT  = C.SDLK_KP_AT

    SDLK_KP_EXCLAM  = C.SDLK_KP_EXCLAM

    SDLK_KP_MEMSTORE  = C.SDLK_KP_MEMSTORE

    SDLK_KP_MEMRECALL  = C.SDLK_KP_MEMRECALL

    SDLK_KP_MEMCLEAR  = C.SDLK_KP_MEMCLEAR

    SDLK_KP_MEMADD  = C.SDLK_KP_MEMADD

    SDLK_KP_MEMSUBTRACT  = C.SDLK_KP_MEMSUBTRACT

    SDLK_KP_MEMMULTIPLY  = C.SDLK_KP_MEMMULTIPLY

    SDLK_KP_MEMDIVIDE  = C.SDLK_KP_MEMDIVIDE

    SDLK_KP_PLUSMINUS  = C.SDLK_KP_PLUSMINUS

    SDLK_KP_CLEAR  = C.SDLK_KP_CLEAR

    SDLK_KP_CLEARENTRY  = C.SDLK_KP_CLEARENTRY

    SDLK_KP_BINARY  = C.SDLK_KP_BINARY

    SDLK_KP_OCTAL  = C.SDLK_KP_OCTAL

    SDLK_KP_DECIMAL  = C.SDLK_KP_DECIMAL

    SDLK_KP_HEXADECIMAL  = C.SDLK_KP_HEXADECIMAL

    SDLK_LCTRL  = C.SDLK_LCTRL

    SDLK_LSHIFT  = C.SDLK_LSHIFT

    SDLK_LALT  = C.SDLK_LALT

    SDLK_LGUI  = C.SDLK_LGUI

    SDLK_RCTRL  = C.SDLK_RCTRL

    SDLK_RSHIFT  = C.SDLK_RSHIFT

    SDLK_RALT  = C.SDLK_RALT

    SDLK_RGUI  = C.SDLK_RGUI

    SDLK_MODE  = C.SDLK_MODE

    SDLK_AUDIONEXT  = C.SDLK_AUDIONEXT

    SDLK_AUDIOPREV  = C.SDLK_AUDIOPREV

    SDLK_AUDIOSTOP  = C.SDLK_AUDIOSTOP

    SDLK_AUDIOPLAY  = C.SDLK_AUDIOPLAY

    SDLK_AUDIOMUTE  = C.SDLK_AUDIOMUTE

    SDLK_MEDIASELECT  = C.SDLK_MEDIASELECT

    SDLK_WWW  = C.SDLK_WWW

    SDLK_MAIL  = C.SDLK_MAIL

    SDLK_CALCULATOR  = C.SDLK_CALCULATOR

    SDLK_COMPUTER  = C.SDLK_COMPUTER

    SDLK_AC_SEARCH  = C.SDLK_AC_SEARCH

    SDLK_AC_HOME  = C.SDLK_AC_HOME

    SDLK_AC_BACK  = C.SDLK_AC_BACK

    SDLK_AC_FORWARD  = C.SDLK_AC_FORWARD

    SDLK_AC_STOP  = C.SDLK_AC_STOP

    SDLK_AC_REFRESH  = C.SDLK_AC_REFRESH

    SDLK_AC_BOOKMARKS  = C.SDLK_AC_BOOKMARKS

    SDLK_BRIGHTNESSDOWN  = C.SDLK_BRIGHTNESSDOWN

    SDLK_BRIGHTNESSUP  = C.SDLK_BRIGHTNESSUP

    SDLK_DISPLAYSWITCH  = C.SDLK_DISPLAYSWITCH

    SDLK_KBDILLUMTOGGLE  = C.SDLK_KBDILLUMTOGGLE

    SDLK_KBDILLUMDOWN  = C.SDLK_KBDILLUMDOWN

    SDLK_KBDILLUMUP  = C.SDLK_KBDILLUMUP

    SDLK_EJECT  = C.SDLK_EJECT

    SDLK_SLEEP  = C.SDLK_SLEEP
)
 // Enumeration of valid key mods (possibly OR'd together).
type Keymod int
const (
    KMOD_NONE Keymod = C.KMOD_NONE

    KMOD_LSHIFT Keymod = C.KMOD_LSHIFT

    KMOD_RSHIFT Keymod = C.KMOD_RSHIFT

    KMOD_LCTRL Keymod = C.KMOD_LCTRL

    KMOD_RCTRL Keymod = C.KMOD_RCTRL

    KMOD_LALT Keymod = C.KMOD_LALT

    KMOD_RALT Keymod = C.KMOD_RALT

    KMOD_LGUI Keymod = C.KMOD_LGUI

    KMOD_RGUI Keymod = C.KMOD_RGUI

    KMOD_NUM Keymod = C.KMOD_NUM

    KMOD_CAPS Keymod = C.KMOD_CAPS

    KMOD_MODE Keymod = C.KMOD_MODE

    KMOD_RESERVED Keymod = C.KMOD_RESERVED
)

 // The SDL virtual key representation.
 // 
 // Values of this type are used to represent keyboard keys using the
 // current layout of the keyboard. These values include Unicode values
 // representing the unmodified character that would be generated by
 // pressing the key, or an SDLK_* constant for those keys that do not
 // generate characters.
type Keycode int32
