/*
Program to verify that the SDL_PIXELFORMAT macros have been properly converted to Go code.
*/

package main

// #cgo linux freebsd darwin pkg-config: sdl2
// #include <SDL.h>
//
// int XXX[] = {SDL_PIXELFLAG(SDL_PIXELFORMAT_UNKNOWN), SDL_PIXELTYPE(SDL_PIXELFORMAT_UNKNOWN), SDL_PIXELORDER(SDL_PIXELFORMAT_UNKNOWN), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_UNKNOWN), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_UNKNOWN), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_UNKNOWN), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_UNKNOWN), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_UNKNOWN), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_UNKNOWN), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_UNKNOWN), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_UNKNOWN),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_INDEX1LSB), SDL_PIXELTYPE(SDL_PIXELFORMAT_INDEX1LSB), SDL_PIXELORDER(SDL_PIXELFORMAT_INDEX1LSB), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_INDEX1LSB), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_INDEX1LSB), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_INDEX1LSB), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_INDEX1LSB), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_INDEX1LSB), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_INDEX1LSB), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_INDEX1LSB), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_INDEX1LSB),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_INDEX1MSB), SDL_PIXELTYPE(SDL_PIXELFORMAT_INDEX1MSB), SDL_PIXELORDER(SDL_PIXELFORMAT_INDEX1MSB), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_INDEX1MSB), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_INDEX1MSB), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_INDEX1MSB), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_INDEX1MSB), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_INDEX1MSB), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_INDEX1MSB), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_INDEX1MSB), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_INDEX1MSB),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_INDEX4LSB), SDL_PIXELTYPE(SDL_PIXELFORMAT_INDEX4LSB), SDL_PIXELORDER(SDL_PIXELFORMAT_INDEX4LSB), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_INDEX4LSB), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_INDEX4LSB), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_INDEX4LSB), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_INDEX4LSB), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_INDEX4LSB), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_INDEX4LSB), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_INDEX4LSB), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_INDEX4LSB),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_INDEX4MSB), SDL_PIXELTYPE(SDL_PIXELFORMAT_INDEX4MSB), SDL_PIXELORDER(SDL_PIXELFORMAT_INDEX4MSB), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_INDEX4MSB), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_INDEX4MSB), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_INDEX4MSB), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_INDEX4MSB), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_INDEX4MSB), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_INDEX4MSB), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_INDEX4MSB), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_INDEX4MSB),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_INDEX8), SDL_PIXELTYPE(SDL_PIXELFORMAT_INDEX8), SDL_PIXELORDER(SDL_PIXELFORMAT_INDEX8), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_INDEX8), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_INDEX8), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_INDEX8), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_INDEX8), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_INDEX8), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_INDEX8), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_INDEX8), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_INDEX8),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGB332), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGB332), SDL_PIXELORDER(SDL_PIXELFORMAT_RGB332), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGB332), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGB332), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGB332), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGB332), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGB332), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGB332), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGB332), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGB332),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGB444), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGB444), SDL_PIXELORDER(SDL_PIXELFORMAT_RGB444), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGB444), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGB444), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGB444), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGB444), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGB444), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGB444), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGB444), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGB444),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGB555), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGB555), SDL_PIXELORDER(SDL_PIXELFORMAT_RGB555), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGB555), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGB555), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGB555), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGB555), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGB555), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGB555), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGB555), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGB555),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_BGR555), SDL_PIXELTYPE(SDL_PIXELFORMAT_BGR555), SDL_PIXELORDER(SDL_PIXELFORMAT_BGR555), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_BGR555), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_BGR555), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGR555), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_BGR555), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_BGR555), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_BGR555), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_BGR555), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_BGR555),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_ARGB4444), SDL_PIXELTYPE(SDL_PIXELFORMAT_ARGB4444), SDL_PIXELORDER(SDL_PIXELFORMAT_ARGB4444), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_ARGB4444), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_ARGB4444), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_ARGB4444), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_ARGB4444), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_ARGB4444), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_ARGB4444), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_ARGB4444), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_ARGB4444),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGBA4444), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGBA4444), SDL_PIXELORDER(SDL_PIXELFORMAT_RGBA4444), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGBA4444), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGBA4444), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGBA4444), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGBA4444), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGBA4444), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGBA4444), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGBA4444), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGBA4444),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_ABGR4444), SDL_PIXELTYPE(SDL_PIXELFORMAT_ABGR4444), SDL_PIXELORDER(SDL_PIXELFORMAT_ABGR4444), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_ABGR4444), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_ABGR4444), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_ABGR4444), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_ABGR4444), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_ABGR4444), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_ABGR4444), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_ABGR4444), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_ABGR4444),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_BGRA4444), SDL_PIXELTYPE(SDL_PIXELFORMAT_BGRA4444), SDL_PIXELORDER(SDL_PIXELFORMAT_BGRA4444), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_BGRA4444), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_BGRA4444), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGRA4444), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_BGRA4444), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_BGRA4444), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_BGRA4444), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_BGRA4444), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_BGRA4444),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_ARGB1555), SDL_PIXELTYPE(SDL_PIXELFORMAT_ARGB1555), SDL_PIXELORDER(SDL_PIXELFORMAT_ARGB1555), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_ARGB1555), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_ARGB1555), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_ARGB1555), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_ARGB1555), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_ARGB1555), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_ARGB1555), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_ARGB1555), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_ARGB1555),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGBA5551), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGBA5551), SDL_PIXELORDER(SDL_PIXELFORMAT_RGBA5551), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGBA5551), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGBA5551), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGBA5551), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGBA5551), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGBA5551), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGBA5551), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGBA5551), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGBA5551),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_ABGR1555), SDL_PIXELTYPE(SDL_PIXELFORMAT_ABGR1555), SDL_PIXELORDER(SDL_PIXELFORMAT_ABGR1555), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_ABGR1555), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_ABGR1555), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_ABGR1555), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_ABGR1555), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_ABGR1555), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_ABGR1555), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_ABGR1555), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_ABGR1555),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_BGRA5551), SDL_PIXELTYPE(SDL_PIXELFORMAT_BGRA5551), SDL_PIXELORDER(SDL_PIXELFORMAT_BGRA5551), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_BGRA5551), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_BGRA5551), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGRA5551), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_BGRA5551), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_BGRA5551), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_BGRA5551), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_BGRA5551), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_BGRA5551),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGB565), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGB565), SDL_PIXELORDER(SDL_PIXELFORMAT_RGB565), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGB565), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGB565), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGB565), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGB565), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGB565), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGB565), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGB565), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGB565),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_BGR565), SDL_PIXELTYPE(SDL_PIXELFORMAT_BGR565), SDL_PIXELORDER(SDL_PIXELFORMAT_BGR565), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_BGR565), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_BGR565), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGR565), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_BGR565), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_BGR565), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_BGR565), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_BGR565), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_BGR565),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGB24), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGB24), SDL_PIXELORDER(SDL_PIXELFORMAT_RGB24), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGB24), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGB24), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGB24), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGB24), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGB24), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGB24), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGB24), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGB24),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_BGR24), SDL_PIXELTYPE(SDL_PIXELFORMAT_BGR24), SDL_PIXELORDER(SDL_PIXELFORMAT_BGR24), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_BGR24), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_BGR24), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGR24), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_BGR24), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_BGR24), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_BGR24), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_BGR24), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_BGR24),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGB888), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGB888), SDL_PIXELORDER(SDL_PIXELFORMAT_RGB888), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGB888), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGB888), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGB888), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGB888), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGB888), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGB888), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGB888), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGB888),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGBX8888), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGBX8888), SDL_PIXELORDER(SDL_PIXELFORMAT_RGBX8888), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGBX8888), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGBX8888), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGBX8888), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGBX8888), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGBX8888), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGBX8888), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGBX8888), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGBX8888),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_BGR888), SDL_PIXELTYPE(SDL_PIXELFORMAT_BGR888), SDL_PIXELORDER(SDL_PIXELFORMAT_BGR888), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_BGR888), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_BGR888), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGR888), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_BGR888), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_BGR888), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_BGR888), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_BGR888), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_BGR888),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_BGRX8888), SDL_PIXELTYPE(SDL_PIXELFORMAT_BGRX8888), SDL_PIXELORDER(SDL_PIXELFORMAT_BGRX8888), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_BGRX8888), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_BGRX8888), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGRX8888), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_BGRX8888), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_BGRX8888), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_BGRX8888), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_BGRX8888), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_BGRX8888),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_ARGB8888), SDL_PIXELTYPE(SDL_PIXELFORMAT_ARGB8888), SDL_PIXELORDER(SDL_PIXELFORMAT_ARGB8888), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_ARGB8888), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_ARGB8888), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_ARGB8888), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_ARGB8888), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_ARGB8888), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_ARGB8888), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_ARGB8888), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_ARGB8888),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_RGBA8888), SDL_PIXELTYPE(SDL_PIXELFORMAT_RGBA8888), SDL_PIXELORDER(SDL_PIXELFORMAT_RGBA8888), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_RGBA8888), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_RGBA8888), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_RGBA8888), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_RGBA8888), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_RGBA8888), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_RGBA8888), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_RGBA8888), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_RGBA8888),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_ABGR8888), SDL_PIXELTYPE(SDL_PIXELFORMAT_ABGR8888), SDL_PIXELORDER(SDL_PIXELFORMAT_ABGR8888), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_ABGR8888), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_ABGR8888), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_ABGR8888), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_ABGR8888), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_ABGR8888), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_ABGR8888), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_ABGR8888), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_ABGR8888),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_BGRA8888), SDL_PIXELTYPE(SDL_PIXELFORMAT_BGRA8888), SDL_PIXELORDER(SDL_PIXELFORMAT_BGRA8888), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_BGRA8888), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_BGRA8888), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_BGRA8888), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_BGRA8888), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_BGRA8888), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_BGRA8888), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_BGRA8888), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_BGRA8888),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_ARGB2101010), SDL_PIXELTYPE(SDL_PIXELFORMAT_ARGB2101010), SDL_PIXELORDER(SDL_PIXELFORMAT_ARGB2101010), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_ARGB2101010), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_ARGB2101010), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_ARGB2101010), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_ARGB2101010), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_ARGB2101010), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_ARGB2101010), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_ARGB2101010), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_ARGB2101010),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_YV12), SDL_PIXELTYPE(SDL_PIXELFORMAT_YV12), SDL_PIXELORDER(SDL_PIXELFORMAT_YV12), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_YV12), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_YV12), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_YV12), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_YV12), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_YV12), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_YV12), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_YV12), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_YV12),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_IYUV), SDL_PIXELTYPE(SDL_PIXELFORMAT_IYUV), SDL_PIXELORDER(SDL_PIXELFORMAT_IYUV), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_IYUV), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_IYUV), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_IYUV), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_IYUV), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_IYUV), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_IYUV), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_IYUV), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_IYUV),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_YUY2), SDL_PIXELTYPE(SDL_PIXELFORMAT_YUY2), SDL_PIXELORDER(SDL_PIXELFORMAT_YUY2), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_YUY2), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_YUY2), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_YUY2), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_YUY2), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_YUY2), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_YUY2), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_YUY2), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_YUY2),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_UYVY), SDL_PIXELTYPE(SDL_PIXELFORMAT_UYVY), SDL_PIXELORDER(SDL_PIXELFORMAT_UYVY), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_UYVY), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_UYVY), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_UYVY), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_UYVY), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_UYVY), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_UYVY), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_UYVY), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_UYVY),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_YVYU), SDL_PIXELTYPE(SDL_PIXELFORMAT_YVYU), SDL_PIXELORDER(SDL_PIXELFORMAT_YVYU), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_YVYU), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_YVYU), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_YVYU), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_YVYU), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_YVYU), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_YVYU), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_YVYU), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_YVYU),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_NV12), SDL_PIXELTYPE(SDL_PIXELFORMAT_NV12), SDL_PIXELORDER(SDL_PIXELFORMAT_NV12), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_NV12), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_NV12), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_NV12), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_NV12), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_NV12), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_NV12), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_NV12), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_NV12),
// SDL_PIXELFLAG(SDL_PIXELFORMAT_NV21), SDL_PIXELTYPE(SDL_PIXELFORMAT_NV21), SDL_PIXELORDER(SDL_PIXELFORMAT_NV21), SDL_PIXELLAYOUT(SDL_PIXELFORMAT_NV21), SDL_BITSPERPIXEL(SDL_PIXELFORMAT_NV21), SDL_BYTESPERPIXEL(SDL_PIXELFORMAT_NV21), SDL_ISPIXELFORMAT_INDEXED(SDL_PIXELFORMAT_NV21), SDL_ISPIXELFORMAT_PACKED(SDL_PIXELFORMAT_NV21), SDL_ISPIXELFORMAT_ARRAY(SDL_PIXELFORMAT_NV21), SDL_ISPIXELFORMAT_ALPHA(SDL_PIXELFORMAT_NV21), SDL_ISPIXELFORMAT_FOURCC(SDL_PIXELFORMAT_NV21)};
//
// extern int XXX[];
import "C"

import (
    "fmt"
    "os"
    "runtime"

    "winterdrache.de/bindings/sdl"
)

var formats = []uint32{sdl.PIXELFORMAT_UNKNOWN, sdl.PIXELFORMAT_INDEX1LSB, sdl.PIXELFORMAT_INDEX1MSB,
    sdl.PIXELFORMAT_INDEX4LSB, sdl.PIXELFORMAT_INDEX4MSB, sdl.PIXELFORMAT_INDEX8,
    sdl.PIXELFORMAT_RGB332, sdl.PIXELFORMAT_RGB444, sdl.PIXELFORMAT_RGB555,
    sdl.PIXELFORMAT_BGR555, sdl.PIXELFORMAT_ARGB4444, sdl.PIXELFORMAT_RGBA4444,
    sdl.PIXELFORMAT_ABGR4444, sdl.PIXELFORMAT_BGRA4444, sdl.PIXELFORMAT_ARGB1555,
    sdl.PIXELFORMAT_RGBA5551, sdl.PIXELFORMAT_ABGR1555, sdl.PIXELFORMAT_BGRA5551,
    sdl.PIXELFORMAT_RGB565, sdl.PIXELFORMAT_BGR565, sdl.PIXELFORMAT_RGB24,
    sdl.PIXELFORMAT_BGR24, sdl.PIXELFORMAT_RGB888, sdl.PIXELFORMAT_RGBX8888,
    sdl.PIXELFORMAT_BGR888, sdl.PIXELFORMAT_BGRX8888, sdl.PIXELFORMAT_ARGB8888,
    sdl.PIXELFORMAT_RGBA8888, sdl.PIXELFORMAT_ABGR8888, sdl.PIXELFORMAT_BGRA8888,
    sdl.PIXELFORMAT_ARGB2101010, sdl.PIXELFORMAT_YV12, sdl.PIXELFORMAT_IYUV,
    sdl.PIXELFORMAT_YUY2, sdl.PIXELFORMAT_UYVY, sdl.PIXELFORMAT_YVYU,
    sdl.PIXELFORMAT_NV12, sdl.PIXELFORMAT_NV21}

func main() {

    runtime.LockOSThread() // SDL functions must all be called from the main thread

    if sdl.Init(sdl.INIT_VIDEO) != 0 {
        fmt.Fprintf(os.Stderr, "SDL_Init Error: %v\n", sdl.GetError())
        os.Exit(1)
    }
    defer sdl.Quit()

    for i := range formats {
        //fmt.Println(strings.Replace("SDL_PIXELFLAG(%), SDL_PIXELTYPE(%), SDL_PIXELORDER(%), SDL_PIXELLAYOUT(%), SDL_BITSPERPIXEL(%), SDL_BYTESPERPIXEL(%), SDL_ISPIXELFORMAT_INDEXED(%), SDL_ISPIXELFORMAT_PACKED(%), SDL_ISPIXELFORMAT_ARRAY(%), SDL_ISPIXELFORMAT_ALPHA(%), SDL_ISPIXELFORMAT_FOURCC(%)", "%", sdl.GetPixelFormatName(formats[i]), -1))
        fmt.Println("----------------------------------------------------------------------------------")
        fmt.Printf("%-30v %2v %2v %2v %2v %2v %2v %5v %5v %5v %5v %5v\n",
            sdl.GetPixelFormatName(formats[i]),
            sdl.PIXELFLAG(formats[i]),
            sdl.PIXELTYPE(formats[i]),
            sdl.PIXELORDER(formats[i]),
            sdl.PIXELLAYOUT(formats[i]),
            sdl.BITSPERPIXEL(formats[i]),
            sdl.BYTESPERPIXEL(formats[i]),
            sdl.ISPIXELFORMAT_INDEXED(formats[i]),
            sdl.ISPIXELFORMAT_PACKED(formats[i]),
            sdl.ISPIXELFORMAT_ARRAY(formats[i]),
            sdl.ISPIXELFORMAT_ALPHA(formats[i]),
            sdl.ISPIXELFORMAT_FOURCC(formats[i]))

        fmt.Printf("%-30v %2v %2v %2v %2v %2v %2v %5v %5v %5v %5v %5v\n",
            sdl.GetPixelFormatName(formats[i]),
            C.XXX[i*11+0],
            C.XXX[i*11+1],
            C.XXX[i*11+2],
            C.XXX[i*11+3],
            C.XXX[i*11+4],
            C.XXX[i*11+5],
            C.XXX[i*11+6] != 0,
            C.XXX[i*11+7] != 0,
            C.XXX[i*11+8] != 0,
            C.XXX[i*11+9] != 0,
            C.XXX[i*11+10] != 0)
    }
}
